Added a page element with a search form.
simonpirko/avia-ticket-c40 pull request #5
Opened 2021-06-15 15:46 UTC by IvanBylinovich

Added a page element with a search form.

2021-06-18 06:33 UTC, SaneaV requested changes

2021-06-18 06:33 UTC, SaneaV commented on src/main/java/by/tms/aviaticket/controller/SearchController.java
> +    @GetMapping("search")
It is a good practice to use "/" in mappings. 
From "search" to "/search"

2021-06-18 06:33 UTC, SaneaV commented on src/main/java/by/tms/aviaticket/controller/TicketController.java
> +@RequestMapping("ticket")
It is a good practice to use "/" in mappings.
From "ticket" to "/ticket"

2021-06-18 06:33 UTC, SaneaV commented on src/main/java/by/tms/aviaticket/controller/TicketController.java
> +    @GetMapping//переход на страница для оформления билета
This mapping needs to have value for mapping.

2021-06-18 06:33 UTC, SaneaV commented on src/main/java/by/tms/aviaticket/controller/SearchController.java
>          if (flights.size() == 0){
The flights.isEmpty () entry looks a little better.

2021-06-18 06:33 UTC, SaneaV commented on src/main/webapp/pages/fragments/filter.html
> +        </div>
It is better to write styles in a special CSS file.

2021-06-18 06:33 UTC, SaneaV commented on src/main/webapp/pages/ticketProcessing.html
> +            <div class="mb-2" style="float:left;width: 50%">
It is better to write styles in a special CSS file.

2021-06-21 15:51 UTC, simonpirko approved these changes

2021-06-21 15:51 UTC, merged